version: "3.7"
services:
  db:
    image: ghusta/postgres-world-db:2.5
    restart: always
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"

  world-viz:
    build:
      context: .
      target: production
    restart: always
    depends_on:
      - db_pop
    links:
    - "db:pgsql-server"

  db_pop:
    build:
      context: .
      target: db_population
    restart: on-failure
    depends_on:
      - db
    links:
    - "db:pgsql-server"

volumes:
  pgadmin-data: