version: "3.7"
services:
  db:
    image: ghusta/postgres-world-db:2.5
    restart: always
    ports:
    - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"

  world-viz:
    image: world-viz:latest

volumes:
  pgadmin-data: